project_id = "tprvyhzpecopryylxznm"

[functions.create-user]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.setup-test-data]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.bulk-delete-users]
verify_jwt = false

[functions.calendar-event]
verify_jwt = false
